source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "bootsnap", require: false
gem "rubyzip", require: "zip"

group :development do
  gem "web-console"
end
